### ISSUE TITLE
Cannot perform multi-threading while crawling on Instagram

### ISSUE THREAD

**Issue by maengsanha** [maengsanha/instacrawler#1]
## 인스타그램 크롤링 성능 상의 문제점

[인스타그램](https://instagram.com)에서 크롤링 시 멀티 쓰레딩이 안되는 문제

1. 크롤링 시 각 pagination 주소를 알고있으면 멀티쓰레딩을 통해 빠른 크롤링이 가능함
2. 인스타그램은 검색 시 스크롤을 내릴 때마다 동적으로 한번에 약 80개의 게시물 정보를 로딩함
3. 요청할 때마다 pagination의 주소가 바뀌고, 그 주소는 이전 pagination에 들어있음
4. 따라서 pagination 주소들을 한번에 알 수 없기 때문에 멀티 쓰레딩이 불가능하고, 현재는 각 pagination을 방문하면서 게시물 정보와 다음 pagination 주소를 얻어와 순차적으로 크롤링을 수행하고 있음.

순차적으로 크롤링하기 때문에 속도가 느리고, 인스타그램 특성 상 게시물이 적게는 1000개부터 많게는 3억개가 넘는데 이를 80개씩 나눠서 일일이 요청을 보내고 응답을 받으면 너무 느림

현재 테스트 결과 1000개의 게시물을 크롤링하는 데 17초 정도가 소요됨

이를 해결할 방법은 크게 2가지로 볼 수 있다

1. n-1번째 pagination과 n번째 pagination 주소의 관계를 찾는다. (불규칙해보여서 불가능해보임)

2. worker를 2개 생성하여 하나는 다음 pagination 값만 크롤링해서 다음 worker에게 넘기고, 다른 worker는 게시물 정보를 파싱한다.

**Comment by parkgeonhu** [comment]
```
worker를 2개 생성하여 하나는 다음 pagination 값만 크롤링해서 
다음 worker에게 넘기고, 다른 worker는 게시물 정보를 파싱한다.
```
이 부분이 맞다고 생각하는데 이것 참 해결하기 어려운 요소야,,

**Comment by maengsanha** [comment]
박하명 교수님 의견
`우선 페이지 주소만 받아온 후 각 페이지를 병렬적으로 크롤링하면 안되겠느냐`

**Comment by parkgeonhu** [comment]
@joshua-dev 그렇게 해서 request를 날리더라도 성능 향상에는 도움이 되려나? 테스트 한번 해봐. end_cursor 를 원하는 만큼 받아서 병렬로 처리했을 때 vs 기존

**Comment by maengsanha** [comment]
20200416 회의 결과

클라이언트에서 도감 생성 시 로딩 시간을 걸고, 그 동안 요청을 보내서 pagination들만 미리 크롤링해서 캐싱한 후 도감이 생성됐을 때 다시 요청을 보내서 크롤링해둔 pagination을 병렬적으로 크롤링한 결과를 보여주는 것으로 시간을 벌 수 있을 것 같음

**Comment by parkgeonhu** [comment]
@joshua-dev 오호 훌륭합니다 test 시간 비교 한번 해주십쇼

**Comment by maengsanha** [comment]
## :white_check_mark: Conflict Fixed

1. Resolved Latency

​	👉🏻 Pagination Caching

 -	/api/v1/crawl 의 Request, Response에 end_cursor 값을 포함시켜 캐싱
 -	크롤링 갯수의 한계와 크롤링 지연 시간을 동시에 해결
 -	모바일 FE에서 스크롤이 최대까지 내려가면 모바일 BE가 업데이트된 end_cursor 값을 포함하여 다시 검색 서버에 요청, 해당 pagination부터 다시 크롤링 수행
 -	end_cursor 값이 비어있을 때 has_next_page가 true라면 크롤링 시작이고, false라면 마지막 pagination까지 크롤링한 것이므로 중단



2. Resolved 404 Error (Page Not Found)

​	👉🏻 Pagination Caching

- end_cursor 값을 캐싱함으로써 어디까지 크롤링했는지 알 수 있으므로 status code가 200이나 429가 아닐 경우 해당 pagination부터 다시 크롤링을 수행, 404 에러가 발생해도 성공할 때까지 시도할 수 있음
- 404 에러가 아주 자주 발생하는 건 아니므로 최대 재시도 횟수를 3번 정도로 제한하고, 그 이상 실패하면 인스타그램의 난독화 매커니즘 발동 시간에 물린 것으로 판단, 처음부터 다시 크롤링 시도



3. Optimized Code

​	👉🏻 OOP → FP

- Crawler 구조체를 삭제하고 Closure를 활용, CrawlerGenerator 정의
- CrawlerGenerator에 Crawler가 저장하던 필드를 bound시키고 CrawlGenerator에 의해 생성된 함수 리터럴을 사용함으로써 Crawl 함수가 Code 영역에서 차지하는 메모리를 절약 가능
- 함수 리터럴을 사용하므로 meta.Search 함수도 단순해짐
